version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: --delete--
  commit-message:
    prefix: "fix(deps):"
    prefix-development: "chore(deps):"
  open-pull-requests-limit: --delete--

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
